#!/bin/sh

#
# generate reg.crt and reg.key file to enable ssl
#
# usage: mreg-gen-ssl <domain-or-ip-for-registry>
#

REG_ADDR="${1:-No registry address or ip provided through argument}"
if [ -n "$GEN_SSL_TARGET_DIR" ]; then cd "$GEN_SSL_TARGET_DIR" || exit 1; fi

# check addr type
ADDR_TYPE="DNS"
expr "$REG_ADDR" \
  : '^[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}\.[[:digit:]]\{1,3\}$' >/dev/null \
  && ADDR_TYPE="IP"

# gen crt & key
openssl req -x509 -newkey rsa:4096 -keyout reg.key -out reg.crt \
  -sha256 -days 3650 -nodes -subj "/CN=$REG_ADDR" \
  -addext "subjectAltName = $ADDR_TYPE:$REG_ADDR" || exit 1

# print info
openssl x509 -in reg.crt -text -noout
